name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main  # or any branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "GitHub Action"

    - name: Push changes to Azure DevOps repository
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        git remote add azure "${{ secrets.AZURE_DEVOPS_REPO_URL }}"
        git push azure --mirror
