name: Sync and Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main  # Adjust this to match the branch you want to sync

jobs:
  sync-and-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Configure Git for commit
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Push changes to Azure DevOps repository
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        git remote add azure "${{ secrets.AZURE_DEVOPS_REPO_URL }}"
        git push azure --mirror

    - name: Trigger Azure DevOps Pipeline
      env:
        AZURE_DEVOPS_ORG_URL: ${{ secrets.AZURE_DEVOPS_ORG_URL }}  # e.g., https://dev.azure.com/yourorg/
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}   # e.g., your-project-name
        AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }} # Pipeline ID to trigger
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}         # Azure DevOps PAT
      run: |
        curl -u :${{ secrets.AZURE_DEVOPS_PAT }} \
          -X POST "${{ secrets.AZURE_DEVOPS_ORG_URL }}${{ secrets.AZURE_DEVOPS_PROJECT }}/_apis/pipelines/${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}/runs?api-version=6.0-preview.1"
